language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install

script:
  - php bin/phpunit -c app/

services: mongodb

notifications:
  email:
    -  jura_n@bk.ru