language: php

php:
    - 5.5
    - 5.6

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install

script:
  - app/console doctrine:mongodb:fixtures:load --env=test --no-interaction
  - php bin/phpunit -c app/

services:
    - mongodb
    - memcached

notifications:
  email:
    -  jura_n@bk.ru