app:
    type: rest
    prefix: /api/users
    resource: "@AppBundle/Resources/config/routing.yml"
    defaults:
        _format: json
    requirements:
        _format: json

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc