parameters:
    user_class: AppBundle\Entity\User

security:

    encoders:
        %user_class%:
            algorithm: bcrypt
            cost:      13

    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        register:
            pattern: ^/api/users/register
            context: app
            anonymous: ~

    access_control:
        - { path: ^/api/users/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, roles: ROLE_USER }