AppBundle\Document\User:
    exclusion_policy: ALL
    properties:
        id:
            type: string
            expose: true
        email:
            type: string
            expose: true
        friends:
            type: array
            expose: true
        requests:
            type: array
            expose: true