AppBundle\Document\User:
    exclusion_policy: ALL
    properties:
        _id:
            serialized_name: id
            type: string
            expose: true
        _email:
            serialized_name: email
            type: string
            expose: true
        _friends:
            serialized_name: friends
            type: array
            expose: true
        _requests:
            serialized_name: requests
            type: array
            expose: true